version: '3'
services:
  db: 
    image: postgres
    container_name: zens_restaurant
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-18012001}
      POSTGRES_DB: "zens_restaurant"
    ports:
      - "5433:5432"
volumes:
  postgres_data: {}
  app-storage: {}
