# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  timeout: 5000
  username: postgres
  password: 18012001
  host: 127.0.0.1
  port: 5433
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # port: 5432

development:
  <<: *default
  database: zens_restaurant

test:
  <<: *default
  database: restaurantdb_test
#
production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
